[[redirects]]
  from = "/football-api/"
  to = "https://api.football-data.org/v4/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"